1. NORMALIZATION PROBLEM

In [17]:
import numpy as np

np.random.seed(115)
X = np.random.rand(5,5)

meanvalue = X.mean()
stdvalue = X.std()

Z = (X-meanvalue)/stdvalue

print("MEAN:", meanvalue)
print("STANDARD DEVIATION:", stdvalue)
print(" ")
print("X:")
print(X)
print(" ")
print("NORMALIZED:")
print(Z)

np.save("X_normalized.npy", Z)

MEAN: 0.5667817272208346
STANDARD DEVIATION: 0.28539720679830755
 
X:
[[0.19609231 0.7027744  0.41369173 0.57680075 0.72787171]
 [0.1905404  0.57311819 0.61419255 0.54398801 0.792635  ]
 [0.54356773 0.40216491 0.08158688 0.71575674 0.99563059]
 [0.14252789 0.15301807 0.20621401 0.93634909 0.80203071]
 [0.90898529 0.96702019 0.77806882 0.89294219 0.31197502]]
 
NORMALIZED:
[[-1.2988544   0.47650317 -0.53641027  0.03510553  0.56444135]
 [-1.31830766  0.02220226  0.16612225 -0.07986663  0.79136468]
 [-0.08133926 -0.57679898 -1.70006866  0.52199184  1.50263861]
 [-1.48653816 -1.44978172 -1.26338911  1.29492283  0.82428623]
 [ 1.19904314  1.40239095  0.74032643  1.1428299  -0.89281431]]


In [21]:
# NUMPY FILE
data = np.load("X_normalized.npy")
print(data) 

[[-1.2988544   0.47650317 -0.53641027  0.03510553  0.56444135]
 [-1.31830766  0.02220226  0.16612225 -0.07986663  0.79136468]
 [-0.08133926 -0.57679898 -1.70006866  0.52199184  1.50263861]
 [-1.48653816 -1.44978172 -1.26338911  1.29492283  0.82428623]
 [ 1.19904314  1.40239095  0.74032643  1.1428299  -0.89281431]]


2. DIVISIBLE BY 3 MATRIX

In [16]:
import numpy as np

numbers = np.arange(1,101)
squares = numbers**2
A = squares.reshape(10,10)
divideby3 = A[A%3==0]

print("MATRIX A SQUARES")
print(A)
print(" ")
print("SQUARES DIVISIBLE BY 3:")
print(divideby3)

np.save("div_by_3.npy", divideby3)

MATRIX A SQUARES
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
 
SQUARES DIVISIBLE BY 3:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [22]:
# NUMPY FILE
data = np.load("div_by_3.npy")
print(data)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
